# Abgabe Hackathon

## Maschinelles Lernen - WiSe 23/24

### Abgabe 04.02.2024, 23:55 Uhr

Ihre Aufgabe während des Hackathons ist die Entwicklung eines Modells zur Voraussage von Hauspreisen anhand von Preisen vergangener Transaktionen auf einem Real-World-Datensatz. 
---

Die **Trainingsdaten** (Ids `1` bis `2000`), auf denen Sie Ihre Modelle trainiert und validiert haben, haben Sie bereits zu Beginn des Hackathons erhalten.

Hier stellen wir Ihnen nun die **Testdaten** (Ids `2001` bis `2919`) zur Verfügung.
Bei den Testdaten fehlt die Spalte `Verkaufspreis`. Die Werte dieser Spalte sollen Sie mithilfe Ihres trainierten Modells voraussagen. 

---

Ihre Abgabe (Zip-Archiv) soll folgende **3 Dateien** umfassen:

* **Beschreibung** *(description.txt)*: Kurze Beschreibung Ihres Modells und Ihrer Datenvorverarbeitung 
* **Modell** *(model.ipynb)*: Ausführbarer Quellcode Ihres Modells und Ihrer Datenvorverarbeitung
* **Predictions** *(predictions.csv)*: Vorhersagen Ihres Modells für alle Testdaten (Ids `2001` bis `2919`) mit Spalten `Id` und `Verkaufspreis`. Das Format soll dem in der Datei `prediction_avg.csv` entsprechen.

In [2]:
# Eingabedaten (ohne Spalte "Verkaufspreis")
import pandas as pd
test = pd.read_csv("test.csv", sep=',', delimiter=None, header='infer', index_col='Id')
test

,Wohngebiet,Nachbarschaft,Bedingung1,Bedingung2,Wohnungsklasse,Gebauedetyp,Wohnungsstil,Baujahr,Umbaujahr,Hausqualitaet,...,Garagenflaeche,Garagenqualitaet,Garagenzustand,EinfahrtGepflastert,Sondermerkmal,SondermerkmalWert,Verkaufsmonat,Verkaufsjahr,Verkaufstyp,Verkaufsbedingung
Id,,,,,,,,,,,,,,,,,,,,,
2001,WN,Flughaf,Norm,Norm,120,StHau,1Sto,1987,1987,7,...,39.60,Du,Du,J,NaN,0.0,9,2018,GarK,Normal
2002,WM,Altstad,Norm,Norm,190,2famU,1.5V,1920,2006,4,...,0.00,NaN,NaN,N,NaN,0.0,6,2018,GarK,Normal
2003,WN,Altstad,Norm,Norm,50,1Fam,1.5V,1910,2008,4,...,25.20,Ar,Du,J,NaN,0.0,3,2016,GarK,Normal
2004,WN,Gallus,Zubr,Norm,70,1Fam,2Sto,1920,2010,4,...,47.52,Du,Du,J,Schu,357.0,10,2016,GarK,Normal
2005,WN,Dornbus,Norm,Norm,20,1Fam,1Sto,1965,2003,5,...,27.27,Du,Du,J,NaN,0.0,11,2019,GeBU,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,WN,Höchst,Norm,Norm,20,1Fam,1Sto,1966,2004,6,...,31.77,Du,Du,J,NaN,0.0,5,2016,GarK,Normal
2916,WN,Westend,Norm,Norm,60,1Fam,2Sto,2003,2004,6,...,42.66,Du,Du,J,NaN,0.0,10,2018,GarK,Normal
2917,WN,Sachsen,EbOA,Norm,85,1Fam,GFoy,1985,1991,5,...,54.99,Du,Du,J,NaN,0.0,1,2017,GarK,Normal
2918,D,Schwanh,Norm,Norm,60,1Fam,2Sto,2016,2016,8,...,94.77,Du,Du,J,NaN,0.0,8,2016,Neu,Unfertig
2919,WN,Hochsch,Norm,Norm,20,1Fam,1Sto,2004,2004,5,...,26.91,Du,Du,J,NaN,0.0,4,2017,GarK,Normal

In [3]:
# Beispiel für Predictions (Spalten "Id" und "Verkaufspreis")
example_predictions = pd.read_csv("prediction_avg.csv", sep=',', delimiter=None, header='infer', index_col='Id')
example_predictions

      Verkaufspreis
Id
2001    153708.4206
2002    153708.4206
2003    153708.4206
2004    153708.4206
2005    153708.4206
...             ...
2915    153708.4206
2916    153708.4206
2917    153708.4206
2918    153708.4206
2919    153708.4206

[919 rows x 1 columns]

In [4]:
# Export von Predictions aus Pandas-Dataframe
example_predictions.to_csv('prediction.csv', sep=',', header=True, index=True)

---